### ISSUE TITLE
Questions about the size of discriminator network

### ISSUE THREAD

**Issue by June01** [VITA-Group/DeblurGANv2#132]
Hi thanks for the excellent work! I hope everything is running well with you guys.

While I am training this network on GOPRO, I found out the size of fake image is [1, 3, 256, 256], which was supposed to be a valid image, right? So I guess the output of a full discriminator should be a value (i.e. [1,1,1]) to indicate if it is real or not. However, I found out the output of full discriminator is [1, 1, 11, 11]. So could you please tell me why it happens? Any quick response is highly appreciated. All the best.

**Comment by June01** [comment]
Btw, here is my config.yaml for reference.
```
---
project: deblur_gan
experiment_desc: fpn

train:
  files_a: &FILES_A /path/to/GOPRO/train/*/blur/*.png
  files_b: &FILES_B /path/to/GOPRO/train/*/sharp/*.png
  size: &SIZE 256
  crop: none #random
  preload: &PRELOAD false
  preload_size: &PRELOAD_SIZE 0
  bounds: [0, .9]
  scope: geometric
  corrupt: &CORRUPT
    - name: cutout
      prob: 0.5
      num_holes: 3
      max_h_size: 25
      max_w_size: 25
    - name: jpeg
      quality_lower: 70
      quality_upper: 90
    - name: motion_blur
    - name: median_blur
    - name: gamma
    - name: rgb_shift
    - name: hsv_shift
    - name: sharpen

val:
  files_a: &FILES_C /path/to/GOPRO/test/*/blur/*.png
  files_b: &FILES_D /path/to/GOPRO/test/*/sharp/*.png
  size: *SIZE
  scope: geometric
  crop: center
  preload: *PRELOAD
  preload_size: *PRELOAD_SIZE
  bounds: [.9, 1]
  corrupt: *CORRUPT

phase: train
warmup_num: 3
model:
  g_name: fpn_inception
  # g_name: InceptionResNet-v2
  blocks: 9
  d_name: double_gan # may be no_gan, patch_gan, double_gan, multi_scale
  d_layers: 3
  content_loss: perceptual
  adv_lambda: 0.001
  # disc_loss: wgan-gp
  disc_loss: gan
  learn_residual: True
  norm_layer: instance
  dropout: True

num_epochs: 200
train_batches_per_epoch: 1000
val_batches_per_epoch: 100
batch_size: 1
image_size: [256, 256]

optimizer:
  name: adam
  lr: 0.0001
scheduler:
  name: linear
  start_epoch: 50
  min_lr: 0.0000001

```
